# Generated by Django 3.0.5 on 2020-05-28 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
